# Generated by Django 4.1.5 on 2023-01-12 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('release_year', models.IntegerField()),
                ('genre', models.CharField(max_length=20)),
                ('star_rating', models.FloatField()),
                ('running_time', models.IntegerField()),
                ('content', models.TextField()),
                ('director', models.CharField(max_length=20)),
                ('actors', models.CharField(max_length=50)),
            ],
        ),
    ]
